// <auto-generated />
using System;
using CIS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS.API.Migrations
{
    [DbContext(typeof(CISDbContext))]
    partial class CISDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS.Assets.Models.AccountPurpose", b =>
                {
                    b.Property<long>("AccountPurposeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountPurposeID"));

                    b.Property<long>("EntityID")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ProductCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductLoan")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductOthers")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductSaleOfROPA")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductSavings")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductTimeDeposit")
                        .HasColumnType("bit");

                    b.Property<string>("PurposeOfAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PurposeOfAccountOther")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AccountPurposeID");

                    b.ToTable("AccountPurpose", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.Address", b =>
                {
                    b.Property<long>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AddressID"));

                    b.Property<string>("BusinessAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("EntityID")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermanentAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PermanentCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermanentZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PresentAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PresentCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PresentZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrincipalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AddressID");

                    b.ToTable("Address", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.BankReview", b =>
                {
                    b.Property<long>("BankReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BankReviewID"));

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("DOSRIType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentsPresented")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmployeePosition")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEntityOwnedByEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntityOwnedByPEP")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNegativeListed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPEPListed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPoracEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRelativeOfEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("NatureOfWorkBusiness")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NatureOfWorkBusinessOther")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RelativeEmployeeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RelativeEmployeePosition")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RelativeRelationship")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("SignatureAuthenticatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BankReviewID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("BankReview", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.Beneficiary", b =>
                {
                    b.Property<long>("BeneficiaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BeneficiaryID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BeneficiaryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NatureOfWork")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrustType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BeneficiaryID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("Beneficiary", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.BusinessInfo", b =>
                {
                    b.Property<long>("BusinessInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessInfoID"));

                    b.Property<string>("AverageAnnualIncome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("BusinessRegExpiry")
                        .HasColumnType("date");

                    b.Property<string>("BusinessRegNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("DTICertExpiry")
                        .HasColumnType("date");

                    b.Property<string>("DTICertNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("DateOfRegistration")
                        .HasColumnType("date");

                    b.Property<bool>("IsGovernment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("NameOfBusiness")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NatureOfBusiness")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlaceOfRegistration")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SizeOfBusiness")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeOfOrganization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeOfOrganizationOther")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BusinessInfoID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("BusinessInfo", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.BusinessInterest", b =>
                {
                    b.Property<long>("BusinessInterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessInterestID"));

                    b.Property<string>("BusinessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("OwnershipPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("BusinessInterestID");

                    b.HasIndex("CustomerID");

                    b.ToTable("BusinessInterest", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.Contact", b =>
                {
                    b.Property<long>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ContactID"));

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("EntityID")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomePhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobilePhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContactID");

                    b.ToTable("Contact", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerID"));

                    b.Property<long?>("AccountPurposeID")
                        .HasColumnType("bigint");

                    b.Property<long?>("AddressID")
                        .HasColumnType("bigint");

                    b.Property<string>("CIDNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ContactID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomerCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("SourceOfFundsID")
                        .HasColumnType("bigint");

                    b.HasKey("CustomerID");

                    b.HasIndex("AccountPurposeID");

                    b.HasIndex("AddressID");

                    b.HasIndex("ContactID");

                    b.HasIndex("SourceOfFundsID");

                    b.ToTable("Customer", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.GovernmentRelation", b =>
                {
                    b.Property<long>("GovernmentRelationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GovernmentRelationID"));

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("HighestPositionOccupied")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PeriodCovered")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GovernmentRelationID");

                    b.HasIndex("CustomerID");

                    b.ToTable("GovernmentRelation", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualEmployment", b =>
                {
                    b.Property<long>("EmploymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmploymentID"));

                    b.Property<string>("AverageMonthlyIncome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("EducationalAttainment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployerBrgyDistrict")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployerBuildingNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployerCityTown")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployerEmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployerPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployerStreet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmploymentStatusOther")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameOfEmployer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NatureOfWork")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OFWCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PositionRank")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeOfEmployment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeOfEmploymentOther")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EmploymentID");

                    b.HasIndex("CustomerID");

                    b.ToTable("IndividualEmployment", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualFamily", b =>
                {
                    b.Property<long>("FamilyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FamilyID"));

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("MotherMaidenGivenName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotherMaidenLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotherMaidenMiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpouseGivenName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpouseLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpouseMiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FamilyID");

                    b.HasIndex("CustomerID");

                    b.ToTable("IndividualFamily", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualForeigner", b =>
                {
                    b.Property<long>("ForeignerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ForeignerID"));

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsACR")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSIRV")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSRRV")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("PassportExpiry")
                        .HasColumnType("date");

                    b.Property<string>("PassportIDNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ForeignerID");

                    b.HasIndex("CustomerID");

                    b.ToTable("IndividualForeigner", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualIdentification", b =>
                {
                    b.Property<long>("IdentificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdentificationID"));

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("DriversLicenseExpiry")
                        .HasColumnType("date");

                    b.Property<string>("DriversLicenseIDNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GSISNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("OtherIDExpiry")
                        .HasColumnType("date");

                    b.Property<string>("OtherIDNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OtherIDType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("PassportIDExpiry")
                        .HasColumnType("date");

                    b.Property<string>("PassportIDNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SSSNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TINNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdentificationID");

                    b.HasIndex("CustomerID");

                    b.ToTable("IndividualIdentification", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualInfo", b =>
                {
                    b.Property<long>("IndividualInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IndividualInfoID"));

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CitizenshipOther")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsResident")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MailingPreference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IndividualInfoID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("IndividualInfo", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.SourceOfFunds", b =>
                {
                    b.Property<long>("SourceOfFundsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SourceOfFundsID"));

                    b.Property<long>("EntityID")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceOfFundsOther")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SourceOfFundsType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SourceOfFundsID");

                    b.ToTable("SourceOfFunds", "cis");
                });

            modelBuilder.Entity("CIS.Assets.Models.BankReview", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithOne("BankReview")
                        .HasForeignKey("CIS.Assets.Models.BankReview", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.Beneficiary", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithOne("Beneficiary")
                        .HasForeignKey("CIS.Assets.Models.Beneficiary", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.BusinessInfo", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithOne("BusinessInfo")
                        .HasForeignKey("CIS.Assets.Models.BusinessInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.BusinessInterest", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithMany("BusinessInterests")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.Customer", b =>
                {
                    b.HasOne("CIS.Assets.Models.AccountPurpose", "AccountPurpose")
                        .WithMany()
                        .HasForeignKey("AccountPurposeID");

                    b.HasOne("CIS.Assets.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID");

                    b.HasOne("CIS.Assets.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactID");

                    b.HasOne("CIS.Assets.Models.SourceOfFunds", "SourceOfFunds")
                        .WithMany()
                        .HasForeignKey("SourceOfFundsID");

                    b.Navigation("AccountPurpose");

                    b.Navigation("Address");

                    b.Navigation("Contact");

                    b.Navigation("SourceOfFunds");
                });

            modelBuilder.Entity("CIS.Assets.Models.GovernmentRelation", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithMany("GovernmentRelations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualEmployment", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualFamily", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualForeigner", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualIdentification", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.IndividualInfo", b =>
                {
                    b.HasOne("CIS.Assets.Models.Customer", "Customer")
                        .WithOne("IndividualInfo")
                        .HasForeignKey("CIS.Assets.Models.IndividualInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIS.Assets.Models.Customer", b =>
                {
                    b.Navigation("BankReview");

                    b.Navigation("Beneficiary");

                    b.Navigation("BusinessInfo");

                    b.Navigation("BusinessInterests");

                    b.Navigation("GovernmentRelations");

                    b.Navigation("IndividualInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
